# Generated by Django 4.1.1 on 2022-09-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminMod_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('mobile_ext', models.CharField(max_length=5)),
                ('mobile', models.IntegerField()),
                ('complaint_description', models.TextField(max_length=500)),
                ('appointment_date_time', models.DateTimeField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
