# Generated by Django 4.1.1 on 2022-10-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMod', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('mobile_ext', models.CharField(max_length=5)),
                ('mobile', models.IntegerField()),
                ('symptoms', models.TextField(max_length=500)),
                ('date', models.DateTimeField(max_length=50)),
                ('time', models.TimeField(max_length=50)),
            ],
        ),
    ]
